# Generated by Django 4.2 on 2023-05-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Bank_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
